apiVersion: v1
kind: Service
metadata:
  name: kubedemoapp-service
spec:
  selector:
    app: kubedemoapp
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30080
  type: NodePort
